version: '3.8'
services:
  db:
    image: ankane/pgvector:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: wishonia_test
    ports:
      - "5432:5432"
    container_name: wishonia-postgres
    volumes:
      - .postgres:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - .redis:/data
    ports:
      - 6379:6379

  pg_dump_data:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./dumps:/dumps
      - ./scripts:/scripts
    command: ["bash", "-c", "pg_dump -a -Fc -v --no-owner -d $$DATABASE_URL -f /dumps/dump_file_name"]

  pg_restore_data:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - ./dumps:/dumps
      - ./scripts:/scripts
    command: ["bash", "-c", "pg_restore -a -v -O -d $$DATABASE_URL_DEST /dumps/dump_file_name"]